config/routes.rb
Rails.application.routes.draw do
  root 'pages#show', page: 'welcome'
  resources :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    page = params[:page]
    render "pages/#{page}"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end

  def create
    @tweet = Tweet.new(params.require(:tweet).permit(:handle, :content))
      if @tweet.save
        redirect_to tweets_path
      else
        render :new
      end
  end

  def new
    @tweet = Tweet.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])

    if @tweet.update_attributes(params.require(:tweet).permit(:handle, :content))
      redirect_to tweets_path
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=tweets_path%>">
        <img alt="Brand" src="http://i.imgur.com/OixHgMI.png">
      </a>
      <!-- <p class="navbar-text navbar-right" id="main-title">Home</p> -->
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Home</a></li>
      </ul>
    </div>
  </div>
</nav>


<%= yield %>

</body>
</html>

app/views/tweets/edit.html.erb
<h1>Edit tweet!</h1>

<%= form_for @tweet do |f| %>

<div>
  <%= f.label :handle %>
  <%= f.text_field :handle %>
</div>

<div>
  <%= f.label :content %>
  <%= f.text_field :content %>
</div>

<%= f.submit "Submit changes" %>
<%= link_to "Cancel", tweet_path %>

<% end %>

app/views/tweets/index.html.erb
<div class="container">
  <h1 class="text-center">Feed</h1>

  <p><%= link_to "Add a new tweet!", new_tweet_path %></p>


  <% @tweets.each do |tweet| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">@<%= tweet.handle %> | <%= time_ago_in_words(tweet.created_at) %> ago </h3>
      </div>
      <div class="panel-body">
        <%= tweet.content %>
        <br>
        <div>
          <%= link_to "More info", tweet_path(tweet) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>Create a new tweet!</h1>

<%= form_for @tweet do |f| %>

<div>
  <%= f.label :handle %>
  <%= f.text_field :handle %>
</div>

<div>
  <%= f.label :content %>
  <%= f.text_field :content %>
</div>

<%= f.submit "Save your tweet" %>

<%= link_to "Back to the list", tweets_path %>

<!-- = button_tag "Cancel", :type => 'button'
 -->

<% end %>



<!-- add clear fields option -->

app/views/tweets/show.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        @<%= @tweet.handle %> at <%= @tweet.created_at.localtime.strftime("%H:%M%P") %> on <%= @tweet.created_at.strftime("%b %d, %Y") %>
      </h4>
    </div>
    <div class="panel-body lead">
      <p><%= @tweet.content %></p>
    </div>
  </div>
  <%= link_to "Edit", edit_tweet_path(@tweet) %>
  <%= link_to "Delete", tweet_path, method: :delete, data: {confirm: "Are you sure you want to delete this tweet?"} %>
</div>